// Generated by tools/build_sprites.py. Do not edit by hand.
window.MQR = window.MQR || {};
MQR.SPRITES = {
 "player_idle": {
  "file": "assets/sprites/player_idle.png",
  "frames": 8,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80,
   160,
   1600,
   80,
   80,
   160,
   1600
  ],
  "bbox": [
   16,
   8,
   48,
   64
  ]
 },
 "player_run": {
  "file": "assets/sprites/player_run.png",
  "frames": 6,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80,
   80,
   80,
   80,
   80
  ],
  "bbox": [
   8,
   8,
   54,
   64
  ]
 },
 "player_jump_up": {
  "file": "assets/sprites/player_jump_up.png",
  "frames": 2,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80
  ],
  "bbox": [
   17,
   0,
   49,
   64
  ]
 },
 "player_jump_mid": {
  "file": "assets/sprites/player_jump_mid.png",
  "frames": 2,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80
  ],
  "bbox": [
   9,
   2,
   56,
   62
  ]
 },
 "player_jump_down": {
  "file": "assets/sprites/player_jump_down.png",
  "frames": 2,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80
  ],
  "bbox": [
   6,
   3,
   57,
   61
  ]
 },
 "frog_green": {
  "file": "assets/sprites/frog_green.png",
  "frames": 5,
  "w": 64,
  "h": 64,
  "ms": [
   800,
   80,
   80,
   80,
   80
  ],
  "bbox": [
   16,
   41,
   48,
   64
  ]
 },
 "frog_red": {
  "file": "assets/sprites/frog_red.png",
  "frames": 5,
  "w": 64,
  "h": 64,
  "ms": [
   800,
   80,
   80,
   80,
   80
  ],
  "bbox": [
   16,
   41,
   48,
   64
  ]
 },
 "frog_blue": {
  "file": "assets/sprites/frog_blue.png",
  "frames": 5,
  "w": 64,
  "h": 64,
  "ms": [
   800,
   80,
   80,
   80,
   80
  ],
  "bbox": [
   16,
   41,
   48,
   64
  ]
 },
 "toucan_fly": {
  "file": "assets/sprites/toucan_fly.png",
  "frames": 4,
  "w": 64,
  "h": 64,
  "ms": [
   80,
   80,
   80,
   80
  ],
  "bbox": [
   9,
   7,
   62,
   44
  ]
 }
};
