"""Turn the animated GIFs from the OPP jungle pack into horizontal sprite strips (PNG) plus a small JS manifest.

Browsers only draw the first frame of an animated GIF onto a canvas, so the game uses these strips instead.
Run from the repository root:   python tools/build_sprites.py      (needs Pillow: pip install pillow)
"""
import json
import os
from PIL import Image, ImageSequence

PACK = os.path.join('assets', 'opp-jungle', 'opp1_jungle_tiles', 'sprites')
OUT = os.path.join('assets', 'sprites')

SPRITES = {
    # name: path inside the pack
    'player_idle': 'humans/traveler/spr_m_traveler_idle_anim.gif',
    'player_run': 'humans/traveler/spr_m_traveler_run_anim.gif',
    'player_jump_up': 'humans/traveler/spr_m_traveler_jump_1up_anim.gif',
    'player_jump_mid': 'humans/traveler/spr_m_traveler_jump_2midair_anim.gif',
    'player_jump_down': 'humans/traveler/spr_m_traveler_jump_3down_anim.gif',
    'frog_green': 'animals/frog/spr_frog_g_idle_anim.gif',
    'frog_red': 'animals/frog/spr_frog_r_idle_anim.gif',
    'frog_blue': 'animals/frog/spr_frog_b_idle_anim.gif',
    'toucan_fly': 'animals/toucan/spr_toucan_fly_anim.gif',
}


def main():
    os.makedirs(OUT, exist_ok=True)
    manifest = {}
    for name, rel in SPRITES.items():
        im = Image.open(os.path.join(PACK, *rel.split('/')))
        frames, ms = [], []
        for f in ImageSequence.Iterator(im):
            frames.append(f.convert('RGBA'))
            ms.append(int(f.info.get('duration', 100)) or 100)
        w, h = frames[0].size
        sheet = Image.new('RGBA', (w * len(frames), h), (0, 0, 0, 0))
        for i, fr in enumerate(frames):
            sheet.paste(fr, (i * w, 0))
        sheet.save(os.path.join(OUT, name + '.png'), optimize=True)
        box = None
        for fr in frames:
            b = fr.getbbox()
            if b:
                box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]), max(box[2], b[2]), max(box[3], b[3]))
        manifest[name] = {'file': 'assets/sprites/%s.png' % name, 'frames': len(frames), 'w': w, 'h': h, 'ms': ms, 'bbox': list(box)}
        print('%-16s %2d frames %dx%d bbox=%s' % (name, len(frames), w, h, box))
    with open(os.path.join('js', 'sprites.js'), 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/build_sprites.py. Do not edit by hand.\n')
        fh.write('window.MQR = window.MQR || {};\nMQR.SPRITES = ' + json.dumps(manifest, indent=1) + ';\n')


if __name__ == '__main__':
    main()